"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { playTurn } from "../../lib/api";

type Action = { key:string; title:string; desc:string; icon:string; asset?:string; once?:boolean; kind:string };
const baseActions: Action[] = [
  { key:"isr", title:"ISR sweep", desc:"Reveal and verify before acting.", icon:"🔎", kind:"sensor" },
  { key:"coalition", title:"Coalition message", desc:"Strengthen public and allied support.", icon:"🤝", kind:"info" },
  { key:"cyber", title:"Cyber operation", desc:"Disrupt command links.", icon:"⚡", kind:"cyber", once:true },
];
const assetActions: Record<string, Action> = {
  carrier:{ key:"carrier_strike", title:"Carrier strike", desc:"Launch long-range air package.", icon:"⚓", asset:"carrier", kind:"strike", once:true },
  f35:{ key:"f35_airstrike", title:"F-35 strike", desc:"Strike key enemy system.", icon:"✈️", asset:"f35", kind:"strike", once:true },
  sub:{ key:"submarine_deploy", title:"Submarine screen", desc:"Contest sea lanes covertly.", icon:"◆", asset:"sub", kind:"sub" },
  patriot:{ key:"missile_defense", title:"Missile defense", desc:"Protect forward base access.", icon:"▲", asset:"patriot", kind:"defense" },
  growler:{ key:"electronic_attack", title:"EW suppression", desc:"Blind radar and targeting.", icon:"📡", asset:"growler", kind:"cyber", once:true },
  p8:{ key:"asw_patrol", title:"ASW patrol", desc:"Hunt underwater threats.", icon:"🔎", asset:"p8", kind:"sensor" },
  aegis:{ key:"aegis_intercept", title:"Aegis intercept", desc:"Defend against missile salvo.", icon:"⚔️", asset:"aegis", kind:"defense" },
  stryker:{ key:"ground_secure", title:"Secure corridor", desc:"Hold roads and evacuation routes.", icon:"▰", asset:"stryker", kind:"ground" },
  mq9:{ key:"drone_watch", title:"Drone overwatch", desc:"Track targets continuously.", icon:"◈", asset:"mq9", kind:"sensor" },
  sof:{ key:"sof_raid", title:"SOF raid", desc:"Hit a fragile node quietly.", icon:"✦", asset:"sof", kind:"strike", once:true },
  sealift:{ key:"logistics_surged", title:"Surge logistics", desc:"Repair sustainment gaps.", icon:"▣", asset:"sealift", kind:"defense" },
};
const mapCfg:any = {
  "Taiwan Strait 2027": { center:[23.8,121.1], zoom:6, why:"Taiwan Strait is shown because the plan depends on sea lanes, Okinawa access, PLA coastal systems, and the Luzon Strait.", label:"Taiwan Strait", red:[[24.2,118.2,"🚀"],[23.5,118.7,"✈️"],[22.5,119.2,"⚓"]], blue:[[25.2,122.1,"⚓"],[24.2,122.7,"◆"],[26.1,127.7,"✈️"]] },
  "NATO Eastern Flank": { center:[53.4,22.6], zoom:6, why:"The NATO Eastern Flank is shown because the plan depends on Poland, Baltic access, allied cohesion, and the Suwalki Gap.", label:"Suwalki Gap", red:[[54.6,25.3,"▰"],[53.9,27.5,"🚀"],[54.9,20.5,"⚓"]], blue:[[52.2,21.0,"▰"],[54.7,18.6,"✈️"],[53.1,23.1,"▲"]] },
  "Embassy Evacuation": { center:[33.33,44.38], zoom:7, why:"The capital evacuation zone is shown because the mission depends on air corridors, roads, embassy access, and harbor/airfield reach.", label:"Capital evacuation zone", red:[[33.45,44.45,"▰"],[33.28,44.54,"🚀"],[33.36,44.25,"⚡"]], blue:[[33.31,44.36,"🚁"],[33.25,44.31,"✦"],[33.5,44.1,"▣"]] },
  "Cyber Infrastructure": { center:[40.75,-74.3], zoom:6, why:"The Northeast grid corridor is shown because the mission depends on substations, command networks, public confidence, and cascading infrastructure risk.", label:"Northeast grid", red:[[40.72,-74.0,"⚡"],[41.1,-73.7,"▣"],[40.2,-75.1,"⚠️"]], blue:[[40.76,-73.9,"🛡️"],[40.4,-74.6,"⚡"],[41.0,-74.2,"🔎"]] },
};
const metricNames = [["intl_opinion","Intl opinion"],["us_domestic","US support"],["red_domestic","Red support"],["allied_confidence","Allied confidence"],["blue_strength","Blue force"],["red_strength","Red force"]];

export default function GamePage(){
  const router = useRouter();
  const mapRef = useRef<HTMLDivElement>(null); const leaflet = useRef<L.Map|null>(null);
  const [scenario,setScenario]=useState("Taiwan Strait 2027"); const [turn,setTurn]=useState(1); const maxTurns=5;
  const [metrics,setMetrics]=useState<any>({intl_opinion:50,us_domestic:72,red_domestic:61,allied_confidence:58,blue_strength:100,red_strength:100});
  const [selected,setSelected]=useState<string>(""); const [used,setUsed]=useState<string[]>([]); const [toast,setToast]=useState(""); const [ghost,setGhost]=useState("Opponent is watching your assumptions, not just your forces.");
  const [redUsed,setRedUsed]=useState<string[]>([]); const [fx,setFx]=useState<any[]>([]); const [history,setHistory]=useState<any[]>([]);
  const actions = useMemo(()=>{ let picked:any[]=[]; try{picked=JSON.parse(localStorage.getItem("warbreak_assets")||"[]")}catch{}; const fromAssets=picked.map(a=>assetActions[a.id]).filter(Boolean); return [...fromAssets,...baseActions].slice(0,6);},[]);
  const cfg:any = mapCfg[scenario] || mapCfg["Taiwan Strait 2027"];
  useEffect(()=>{ setScenario(localStorage.getItem("warbreak_scenario") || "Taiwan Strait 2027"); },[]);
  useEffect(()=>{ if(!mapRef.current || leaflet.current) return; const cfgNow:any=mapCfg[localStorage.getItem("warbreak_scenario") || "Taiwan Strait 2027"] || cfg; const m=L.map(mapRef.current,{center:cfgNow.center as any,zoom:cfgNow.zoom,zoomControl:false,attributionControl:false,dragging:true,scrollWheelZoom:true}); leaflet.current=m; L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd", maxZoom:19}).addTo(m); setTimeout(()=>{ const c=m.getContainer(); c.classList.add("war-map-tilt"); },50); const icon=(cls:string,emoji:string)=>L.divIcon({html:`<div class="marker ${cls}">${emoji}</div>`,className:"",iconSize:[34,34],iconAnchor:[17,17]}); cfgNow.blue.forEach((p:any)=>L.marker([p[0],p[1]],{icon:icon("blue",p[2])}).addTo(m)); cfgNow.red.forEach((p:any)=>L.marker([p[0],p[1]],{icon:icon("red",p[2])}).addTo(m)); },[scenario]);
  const sound=(type:string)=>{ try{ const ctx=new AudioContext(); const o=ctx.createOscillator(); const g=ctx.createGain(); o.connect(g); g.connect(ctx.destination); o.frequency.value=type==="boom"?70:type==="sonar"?440:type==="cyber"?880:260; g.gain.value=.09; o.start(); g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45); o.stop(ctx.currentTime+.5);}catch{} };
  const animate=(kind:string)=>{ const id=Date.now()+Math.random(); const cls=kind==="sub"||kind==="sensor"?"sonar":kind==="cyber"?"cyber":"explosion"; setFx(f=>[...f,{id,cls}]); sound(cls==="explosion"?"boom":cls==="sonar"?"sonar":"cyber"); setTimeout(()=>setFx(f=>f.filter(x=>x.id!==id)),1700); if(leaflet.current){ const pts=cfg.red[0]; leaflet.current.flyTo([pts[0],pts[1]], cfg.zoom+1, {duration:.8}); if(kind==="strike"){ const from=cfg.blue[0], to=cfg.red[0]; const line=L.polyline([[from[0],from[1]],[to[0],to[1]]],{color:"#e5d28c",weight:3,className:"arc"}).addTo(leaflet.current); setTimeout(()=>line.remove(),1300); } } };
  const execute=async()=>{ const act=actions.find(a=>a.key===selected)||actions[0]; if(!act) return; if(act.once && used.includes(act.key)){ setToast("That one-time action has already been used. Choose a new response."); setTimeout(()=>setToast(""),1900); return; } if(act.once) setUsed(u=>[...u,act.key]); animate(act.kind); const redAsset = act.kind==="strike"?"mobile air defense + information response":act.kind==="sub"?"diesel-electric submarine screen":act.kind==="cyber"?"cyber / electronic disruption cell":act.kind==="defense"?"missile pressure and decoys":"media pressure + observation network"; setRedUsed(r=>Array.from(new Set([...r, redAsset]))); let reply="Ghost Council: Red pressures the assumption behind your move, not just the unit you moved."; try{ const gid=localStorage.getItem("warbreak_game_id")||"local-demo"; const res=await playTurn(gid, act.title); reply=res.ghost_response || res.ghost_reasoning || res.red_move || reply; setMetrics((m:any)=>({...m,...(res.metrics||res.game_state||{})})); }catch{ reply="Backend unavailable. Visual simulation continues; AI response could not be loaded."; }
    setGhost(reply); setHistory(h=>[...h,{turn, action:act.title, red:redAsset}]); if(turn>=maxTurns){ localStorage.setItem("warbreak_history",JSON.stringify([...history,{turn,action:act.title,red:redAsset}])); localStorage.setItem("warbreak_metrics",JSON.stringify(metrics)); localStorage.setItem("warbreak_red_used",JSON.stringify(Array.from(new Set([...redUsed,redAsset])))); router.push("/autopsy"); } else setTurn(t=>t+1); };
  return <main className="game"><div className="topbar"><div className="brand"><button className="btn ghost" onClick={()=>router.push('/')}>← Exit</button> WARBREAK <span className="badge">{scenario}</span></div><div><span className="badge">Turn {turn}/{maxTurns}</span> <span className="badge">Active</span></div></div><div className="game-layout"><section className="map-stage"><div ref={mapRef} className="map3d"/><div className="map-overlay"/><div className="scanline"/><div className="stage-hud"><div className="note">3D map · drag to pan/orbit · scroll to zoom · keys 1–6</div><div className="note dark">Why this area? {cfg.why}</div></div>{fx.map(x=><div key={x.id} className={`fx ${x.cls}`} style={{left:"54%",top:"45%"}} />)}{toast&&<div className="toast">{toast}</div>}<div className="execute-row"><input className="command-input" placeholder="Optional custom command…"/><button className="btn primary" onClick={execute}>EXECUTE SELECTED →</button></div><div className="actions-dock">{actions.map((a,i)=><button key={a.key} onClick={()=>setSelected(a.key)} className={`action-card ${selected===a.key?"selected":""} ${used.includes(a.key)?"used":""}`}><h4>{i+1}. {a.icon} {a.title}</h4><p>{a.desc}</p>{used.includes(a.key)&&<span className="small">Used</span>}</button>)}</div></section><aside className="sidebar"><div className="side-card"><h3>Information battlefield</h3>{metricNames.map(([k,n])=><div className="metric" key={k}><div className="metric-head"><span>{n}</span><b>{Math.round(metrics[k]??50)}</b></div><div className="bar"><span style={{width:`${Math.max(0,Math.min(100,metrics[k]??50))}%`}}/></div></div>)}</div><div className="side-card"><h3>Ghost Council</h3><p>{ghost}</p></div><div className="side-card"><h3>Red assets used against us</h3>{redUsed.length?redUsed.map((r,i)=><p key={i} className="small">• {r}</p>):<p className="small">No enemy asset has been committed yet.</p>}</div><div className="side-card"><h3>Mission log</h3>{history.map(h=><p key={h.turn} className="small">T{h.turn}: Blue used {h.action}. Red answered with {h.red}.</p>)}</div></aside></div></main>;
}
